### ISSUE TITLE
ESP32 measureHighPrecision(): Not enough data received

### ISSUE THREAD

**Issue by T365** [Sensirion/arduino-i2c-sht4x#4]
measureHighPrecision(): Not enough data received

**Comment by quentin-cy** [comment]
Hej @T365 
We will need a bit more information to help you there.
What is your setup ?
Do other command work ?
Are you running the example code ?

**Comment by psachs** [comment]
"Not enough data received" is usually an issue with the sensor connection. E.g. there is too much noise or the i2c signal is out of specs.
In some cases the issue is only visible with high precision measurements but not with low precision. Using a developer board (e.g. from Adafruit or Seed) should also not cause any problems.

For ESP32 you can use the built-in pull-up resistors. Please refer to the datasheet  "1 Quickstart", "section 4.2" and "table 4" for the recommended circuit and capacitor to use between ground and VDD:
https://www.sensirion.com/resource/datasheet/sht4x
