### ISSUE TITLE
Incompatibility Issue

### ISSUE THREAD

**Issue by DiSkyMaster** [Sensirion/arduino-i2c-sht4x#5]
I am currently undertaking a project involving the integration of the [SHT40I-AD1B-R2](https://jlcpcb.com/partdetail/Sensirion-SHT40I_AD1BR2/C3664342) temperature sensor with an ESP32 C3 Mini, as depicted in the attached image. I am employing the Sensirion Arduino-I2C-SHT4x library to facilitate this integration. Unfortunately, I have encountered a significant issue where the library fails to read the data from the sensor, specifically, it does not detect or recognize the SHT sensor. The system consistently returns an error message.

Given this context, I would greatly appreciate any guidance or recommendations you might have regarding this problem. Could there be specific configurations or aspects of the SHT40I that are not compatible with your library? Any insights or potential solutions to enable successful communication between the sensor and the microcontroller would be immensely helpful.

Thank you for your assistance.

![image](https://github.com/Sensirion/arduino-i2c-sht4x/assets/101949465/e39a0d86-ea4b-4034-ad5f-8d86a6b492a6)

**Comment by sdmueller** [comment]
Hi @DiSkyMaster 

The library should be compatible with the SHT40I.

Did you draw the schematic with the pins corresponding to their physical location?
Because then your pin assignment looks off. SDA should be opposite from VSS and SCL should be opposite from VDD.

See excerpt from the datasheet:
![image](https://github.com/Sensirion/arduino-i2c-sht4x/assets/11133894/9cc0db29-bca4-4b81-a53e-6dbf4c006528)

Can you double check if you have the correct pin assignment?
